# Configuration file for SuperHoppersWebUI
# Port for the web server
Port: 8080
# Default language of the plugin
Language: en
# Default language of the UI
UILanguage: en
# Update interval in ticks (20 ticks = 1 second)
UpdateInterval: 6000


#versions (don't touch)
versions:
    config: 1
    web: 1