# Configuration file for SuperHoppersWebUI
# Port for the web server
Port: 8080
# Update interval in seconds
Interval: 180
# Debug Mode (It will show more information in the console, but will also spam your server console)
DebugMode: false

#versions (don't touch)
versions:
    config: 1
    web: 1