# Configuration file for SuperHoppersWebUI
# Port for the web server
Port: 8080
# Default language of the plugin
Language: en
# Update interval in seconds
Interval: 1800


#versions (don't touch)
versions:
    config: 1
    web: 1