name: SuperHoppersWebUI
version: '${project.version}'
main: org.cptgum.superhopperswebui.Main
api-version: '1.20'
author: CptGummiball
depend: [SuperHoppers]
load: POSTWORLD

commands:
  sui:
    description: 'Main command for SuperHoppersWebUI.'
    usage: /sui <link|restart>

permissions:
  sui.link:
    description: 'Allows to trigger the link command.'
    default: op
  sui.restart:
    description: 'Allows to restart the WebUI Server'
    default: op